### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/apn#1]
Let me know when you're done with the initial code / tests / readme. I'll do a code review and set up packages, and other services

**Comment by barryvdh** [comment]
Ok, done.

I've imported this from my previous project, didn't have chance to test this in a 'live' app. Not 100% sure about the ServiceProvider though, if that's the best way.

**Comment by luisdalmolin** [comment]
This package is not registered in packagist, right? If you guys publish I can test in a sandbox and in a few weeks in production too.

**Comment by barryvdh** [comment]
@freekmurze @mpociot Anything holding back the review?

**Comment by freekmurze** [comment]
Sorry, forgot about this. Thanks for reminding me. I'll take a look now.

**Comment by freekmurze** [comment]
Done

Please take a look at #7 

I've also registered the package on Packagist and configured StyleCI / Insights / Scrutinizer
