### ISSUE TITLE
The Apple Push Notification service (APNs) will no longer support the legacy binary protocol as of November 2020

### ISSUE THREAD

**Issue by rajmohan6535** [laravel-notification-channels/apn#100]
Does anyone see some tasks required to do to fully support this?

**Comment by dwightwatson** [comment]
We use [pushok](https://github.com/edamov/pushok) under the hood.

As far as I can tell, they use the latest APIs and so this shouldn't be an issue for us.

**Comment by rajmohan6535** [comment]
For clarification: Do we need to change any updates on certificates or any files related to this?

**Comment by dwightwatson** [comment]
As far as I understand, no. The APIs we are using are current.

**Comment by rajmohan6535** [comment]
Ok thanks bro
