### ISSUE TITLE
On-Demand Notifications

### ISSUE THREAD

**Issue by dinhdanh** [laravel-notification-channels/apn#105]
I need to send a notification to someone who is not stored as a "user" of my application. How can I do this?
For instance, in a lot of laravel built in driver:
```
Notification::route('mail', 'taylor@example.com')
        ->route('nexmo', '5555555555')
        ->route('slack', 'https://hooks.slack.com/services/...')
        ->notify(new InvoicePaid($invoice));
```
Any ideas? I've tried this but not work
```
Notification::route(ApnChannel::class, 'device-token')
    ->notify(new InvoicePaid($invoice));
```

**Comment by dwightwatson** [comment]
Looks like you need to use the key `apn`.

```
Notification::route('apn', 'device-token');
```

**Comment by dinhdanh** [comment]
> Looks like you need to use the key `apn`.
> 
> ```
> Notification::route('apn', 'device-token');
> ```

Do I need to declare ApnChannel somewhere? I tried and got this error:
`Driver [apn] not supported.`

**Comment by dwightwatson** [comment]
I think you still need to use the `ApnChannel::class` in the notification, you just use `apn` for an on-demand notification.

**Comment by dinhdanh** [comment]
> I think you still need to use the `ApnChannel::class` in the notification, you just use `apn` for an on-demand notification.

It works perfectly on my release build (via xcode on my mac), but it's not work on testflight version. Do you have any idea?
Another question, is this package support background notification. Cancel call is an example use case. Thanks so much

**Comment by dwightwatson** [comment]
Not sure - sounds like that's going to be an issue with your Apple configuration, rather than the package.

I think if you need more complex interactions you'll probably need to integrate directly - I'm not sure the the notification channels would be the best approach for that sort of setup.
