### ISSUE TITLE
Message : Undefined offset: in KeyConverter.php

### ISSUE THREAD

**Issue by prafful-panwar-ayur** [laravel-notification-channels/apn#111]
Message : Undefined offset: 0 Line : 214 File: C:\xampp\htdocs\{{projectFolder}}\vendor\web-token\jwt-key-mgmt\KeyConverter\KeyConverter.php

**Comment by dwightwatson** [comment]
Not a whole lot of information to work with here. Are you sure you’ve set up the config correctly?

**Comment by prafful-panwar** [comment]
Yeah as its says in documents i followed all the steps in sequence. 

Error is in this page here :

KeyConverter.php

`private static function sanitizePEM(string &$pem): void
    {
        preg_match_all('#(-.*-)#', $pem, $matches, PREG_PATTERN_ORDER);
        $ciphertext = preg_replace('#-.*-|\r|\n| #', '', $pem);

        $pem = $matches[0][0].PHP_EOL;
        $pem .= chunk_split($ciphertext, 64, PHP_EOL);
        $pem .= $matches[0][1].PHP_EOL;
    }`

**Comment by prafful-panwar** [comment]
```
# iOS Push Notification
APN_KEY_ID=7VL69J7V42
APN_TEAM_ID={{TEAMID}}
APN_BUNDLE_ID={{bundleId}}
APN_PRIVATE_KEY=/storage/keyName.p8
APN_PRODUCTION=true
```

**Comment by prafful-panwar** [comment]
@dwightwatson 

Yeah as its mentioned in documents i followed all the steps. 

Error is coming from sanitizePEM function in KeyConverter.php file 

```
private static function sanitizePEM(string &$pem): void
    {
        preg_match_all('#(-.*-)#', $pem, $matches, PREG_PATTERN_ORDER);
        $ciphertext = preg_replace('#-.*-|\r|\n| #', '', $pem);

        $pem = $matches[0][0].PHP_EOL;
        $pem .= chunk_split($ciphertext, 64, PHP_EOL);
        $pem .= $matches[0][1].PHP_EOL;
    }
```

**Env variable related to APN**

```
# iOS Push Notification
APN_KEY_ID=7VL69J7V42
APN_TEAM_ID={{TEAMID}}
APN_BUNDLE_ID={{bundleId}}
APN_PRIVATE_KEY=/storage/keyName.p8
APN_PRODUCTION=true
```

**Updated the code in config/broadcasting.php config file**

```
'apn' => [
            'key_id' => env('APN_KEY_ID'),
            'team_id' => env('APN_TEAM_ID'),
            'app_bundle_id' => env('APN_BUNDLE_ID'),
            'private_key_content' => env('APN_PRIVATE_KEY'),
            'production' => env('APN_PRODUCTION', true),
],
```

**Notification file**

```
use Illuminate\Bus\Queueable;
use NotificationChannels\Apn\ApnChannel;
use NotificationChannels\Apn\ApnMessage;
use Illuminate\Notifications\Notification;

class CallAppointmentNotification extends Notification
{

    use Queueable;

    public function via($notifiable)
    {
        return [ApnChannel::class];
    }

    public function toApn($notifiable)
    {
        return ApnMessage::create()
            ->badge(1)
            ->title('Account approved')
            ->body("Your got a call Appointment!");
    }
}
```

**User Model**

```
public function routeNotificationForApn()
    {
        return 'apnTokenFromiOSApplication'; // For testing passing hard coded token
    }
```

**Comment by dwightwatson** [comment]
That key converter file you're referencing isn't part of this package, it's a dependency. It sounds like it's erroring because the key it's receiving isn't in the correct format. Confirm that the credentials are correct and that they're getting to `sanitizePEM` correctly.

**Comment by prafful-panwar** [comment]
@dwightwatson same key and credentials i am using in another app with https://github.com/davibennun/laravel-push-notification package and its working fine but as that package is not being updated since long time i tried this package but facing issue. 

I am using Laravel 8.* and tired with both .p8 file and .pem file but no luck. :(

**Comment by dwightwatson** [comment]
Unfortunately I can't really provide any more assistance here - this notification channel is really just a wrapper around the [`pushok`](https://github.com/edamov/pushok) library, and it's known to be working in production, so the issue must be on your end. From the error message it sounds like it's an issue with the credentials but as that's something this channel doesn't really interface with apart from forwarding it into `pushok` I'm not sure what else to suggest. You can always play with `pushok` directly and see if you can make any progress there.

**Comment by prafful-panwar** [comment]
@dwightwatson you can close the issue as i am using https://github.com/Edujugon/PushNotification package and its working fine with the same .pem file. 

Thanks anyway. :)
