### ISSUE TITLE
Possible to support collapsing notifications

### ISSUE THREAD

**Issue by dmyers** [laravel-notification-channels/apn#114]
Is it possible to set the payload param `apns-collapse-id` which allows for collapsing notifications to be handled by iOS?

Or is it possible to customize the payload with additional options like an array as another good parameter for notifications is `priority` and `subtitle`.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/

**Comment by dwightwatson** [comment]
Don't believe we have that functionality now but happy to accept a PR that supports a collapse configuration or provides a way to pass an array for additional custom configuration. We seem to get a lot of these popping up and we add one feature at a time so providing a back door for those who need specific configuration is a good idea.

**Comment by nielsiano** [comment]
Adding the functionality to create the payload by hand instead restricting developers to use the setters in `ApnMessage` would be nice.

**Comment by dwightwatson** [comment]
Yeah, I don't see any reason why we shouldn't support a standalone Pushok\Notification as well as the ApnMessage which we have to adapt under the hood. That's probably a better solution for all these edge cases.

Happy to accept a PR that would add this functionality.

**Comment by dwightwatson** [comment]
Added by #130 and available in v3.8.0.
