### ISSUE TITLE
How do I troubleshoot problems I'm having with this package?

### ISSUE THREAD

**Issue by benpva16** [laravel-notification-channels/apn#116]
I have followed the documentation on the main page, and when I try to send an apn notification, I can log on the server that the constructor and via methods are called, but I can't figure out why my notification either isn't being sent or isn't being received. My logs have no info from the package either.

How do I troubleshoot this? What am I missing?

MyNotification.php
```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Log;
use NotificationChannels\Apn\ApnChannel;
use NotificationChannels\Apn\ApnMessage;

class MyNotification extends Notification
{
    use Queueable;

    public function __construct()
    {
        Log::debug('MyNotification constructor called');
    }

    public function via($notifiable)
    {
        Log::debug('MyNotification via called');
        return [ApnChannel::class];
    }

    public function toApn($notifiable)
    {
        Log::debug('MyNotification toApn called');
        return ApnMessage::create()
            ->badge(1)
            ->title('My title')
            ->body('My body');
    }

    public function routeNotificationForApn($notifiable)
    {
        Log::debug('MyNotification routeNotificationForApn called');
        return $notifiable->token;
    }
}
```

usage code in MyController.php
```
    public function sendNotification(MyModel $model)
    {
    // authorization checks here...

        $devices = Device::where('user_id', $model->user_id)->get();
        Notification::send($devices, new MyNotification());

        return response()->json(null, 200);
    }
```

**Comment by dwightwatson** [comment]
Unfortunately there's not really enough information here to go on.

Some sanity checks:
* Are you sure there are `$devices` would trigger being sent to?
* Are you sure there is no queuing going on?

**Comment by benpva16** [comment]
@dwightwatson Thank you for your response. Yes, $devices has one device, and I removed the use Queueable; line in the MyNotification.php file

**Comment by benpva16** [comment]
Here are the relevant sections of my broadcasting.php and .env files
<img width="688" alt="Screen Shot 2021-01-29 at 4 54 10 PM" src="https://user-images.githubusercontent.com/14826711/106336222-0ffdd380-6254-11eb-9a71-1125eec7ffa7.png">
![Screen Shot 2021-01-29 at 4 55 00 PM](https://user-images.githubusercontent.com/14826711/106336226-12f8c400-6254-11eb-9f77-a30b66a7c94d.png)

**Comment by mnordstr** [comment]
Isn't the routeNotificationForApn() method supposed to be in the notifiable model (Device in your case)?

Now you have it in the notification class itself.

**Comment by benpva16** [comment]
@mnordstr That was the problem! I either misread the documentation or did not read it carefully enough. Thank you both for your help.

To recap, MyNotification.php should be:
```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Log;
use NotificationChannels\Apn\ApnChannel;
use NotificationChannels\Apn\ApnMessage;

class MyNotification extends Notification
{
    use Queueable;

    public function __construct()
    {
        Log::debug('MyNotification constructor called');
    }

    public function via($notifiable)
    {
        Log::debug('MyNotification via called');
        return [ApnChannel::class];
    }

    public function toApn($notifiable)
    {
        Log::debug('MyNotification toApn called');
        return ApnMessage::create()
            ->badge(1)
            ->title('My title')
            ->body('My body');
    }
}
```

Device.php should be:
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Device extends Model
{
    use HasFactory, Notifiable;

    public function routeNotificationForApn($notifiable)
    {
        return $this->token;
    }
}

```
