### ISSUE TITLE
Allow support for $subtitle

### ISSUE THREAD

**Issue by r0hitch0pra** [laravel-notification-channels/apn#125]
Pushok support $subtitle via the setSubtitle method. Can that be added to this package?

**Comment by dwightwatson** [comment]
I’ll accept a PR with tests that adds this

**Comment by r0hitch0pra** [comment]
@dwightwatson, can you give me access to push? I've finished this implementation.

**Comment by dwightwatson** [comment]
I can't give you access to push, you'll need to make a PR from your branch into this repo.

**Comment by r0hitch0pra** [comment]
Done. Thanks!
