### ISSUE TITLE
Target [Pushok\AuthProviderInterface] is not instantiable while building [Pushok\Client]

### ISSUE THREAD

**Issue by gienmangaliman** [laravel-notification-channels/apn#127]
Encountered when running ` Notification::send(Auth::user(), new AccountApproved([]));`

**Comment by dwightwatson** [comment]
Sounds almost like the service provider hasn't' been registered? What version of Laravel are you using, and is it correctly registering the service provider?

**Comment by gienmangaliman** [comment]
> Sounds almost like the service provider hasn't' been registered? What version of Laravel are you using, and is it correctly registering the service provider?

hey @dwightwatson I'm using laravel 8..how should I call the Pushok in the service provider app.php?

**Comment by dwightwatson** [comment]
It should be registered automatically when you do a `composer install` - is there any reason it may not be?

I'm using this in production now with a Laravel app, so not sure what's going wrong here - going to need some more information to get to the bottom of this.

**Comment by gienmangaliman** [comment]
![image](https://user-images.githubusercontent.com/70508040/120959471-693ebc00-c78c-11eb-9ec3-e4d14879c636.png)
laravel-notification-channels/apn          v3.6.0             Apple APN Push Notification Ch

hmm im not so sure..it is installed tho.. im testing it in my local

**Comment by dwightwatson** [comment]
```
>>> app(Pushok\Client::class)
=> Pushok\Client {#5283}
``` 

When I try to create an instance of the pushok client in tinker it works fine - I assume it will blow up when you try.  If that's the case there is something wrong with your installation. See if you can replicate it on a fresh Laravel install.

**Comment by gienmangaliman** [comment]
did run it in tinker as well but the error still persist.. re installed the library as well

![image](https://user-images.githubusercontent.com/70508040/120960305-1e25a880-c78e-11eb-9fa1-ac437011da22.png)

**Comment by gienmangaliman** [comment]
@dwightwatson this should also work for safari macOS right?

**Comment by dwightwatson** [comment]
Not entirely sure. Though from having a very quick browse it does look like it goes through APNs too. However, I've personally only used it with iOS push notifications.

**Comment by gienmangaliman** [comment]
I see.. so this library only works if I have an apple app? doesnt work in safari ios or mac os? 🤔

**Comment by dwightwatson** [comment]
No, all I said was I've only personally used it with iOS. But if Mac/Safari use APNs too then it should work for that as well. 

However you will need to solve the installation problem first. And it's not clear what is broke yet.

**Comment by gienmangaliman** [comment]
yea..okay..have you instantiated your pushok in app.php?

**Comment by dwightwatson** [comment]
No, because Laravel's automatic service discovery should be picking the service provider up for you. It sounds like perhaps it isn't for you, so you should try adding the service provider to your config/app.php file and see if that changes anything.

**Comment by gienmangaliman** [comment]
What Service Provider should I include tho? Apparently there's no ServiceProvider file in the src 😕 

![image](https://user-images.githubusercontent.com/70508040/121006976-1aad1400-c7c4-11eb-9c5c-da37c553bc81.png)

**Comment by dwightwatson** [comment]
You're looking at the source code for pushok. 

You need to look at the source code for this notification channel - the service provider is here: https://github.com/laravel-notification-channels/apn/blob/master/src/ApnServiceProvider.php

**Comment by gienmangaliman** [comment]
aaah! thanks dwight..it's working now.. I mean the target error is gone, at least.. I should have done this earlier but I was including the pushOk instead if the apn provider  🤦  I have a new error tho .. have you experienced this? Based on my set up I dont remember including any pem files tho

Also, should I create another thread for this issue?

![image](https://user-images.githubusercontent.com/70508040/121009835-3534bc80-c7c7-11eb-8a68-ab28d7e18ed9.png)

**Comment by dwightwatson** [comment]
It sounds like you haven't configured the credentials properly. Please read through the installation instructions on the readme and check the pushok docs if you are doing something custom. You should have all your credentials in your Apple developer account.

**Comment by gienmangaliman** [comment]
hmmm I pretty much configured everything from https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW1 up to creating the APNs key in https://developer.apple.com/ I create a web push ID instead of app ID tho, should that matter?

another question.. in the broadcasting config > apn > private_key_content the value that I should set would be the content of my .p8 file that I have downloaded after generating the APNs key in developer.apple?

**Comment by gienmangaliman** [comment]
hi @dwightwatson no more error on the key converter, just had to update the `private_key_content`.. although whenever I'm running `Notification::send(Auth::user(), new AccountApproved([]));` it still doesn't show any notification banner on my macOS. any idea why? or where should I look for error logs?

**Comment by dwightwatson** [comment]
I'm sorry, but that's really outside the scope of this package. This package is simply a wrapper around pushok to make it work with Laravel's notification channels, so anything that isn't working beyond that is not something I can help with.

The best thing to do is to drop a `dd($response)` inside the `ApnChannel` class (https://github.com/laravel-notification-channels/apn/blob/master/src/ApnChannel.php#L92) and inspect the actual pushok responses - it will provide some insight into whether APNs is accepting the pushes, or show error information if there is any. Alternatively, hook your Laravel app up to listen to the `Illuminate\Notifications\Events\NotificationFailed` event to access the same information.

**Comment by gienmangaliman** [comment]
alright. will do that @dwightwatson thank you so much!
