### ISSUE TITLE
change environment to production 

### ISSUE THREAD

**Issue by beyondthepale** [laravel-notification-channels/apn#133]
I am using this package with Laravel 8. I found that including the production key as part of 'apn' in 'connections' in the broadcasting config failed to alter the environment from development to production. The only way that I could change the environment to production was to use the Pushok library.

This did not work.

broadcasting.php

'connections' => [

        'apn' => [
   
            'production' => env('APN_PRODUCTION', true),
        ],
],

This did not work either.

namespace App\Notifications;

$options = [
'production' => true,
];
$customClient = new \Pushok\Client(\Pushok\AuthProvider\Token::create($options));

Instead I used this which worked.

namespace App\Notifications;

$authProvider = AuthProvider\Token::create($options);
$customClient = new \Pushok\Client($authProvider, $production = true);

**Comment by dwightwatson** [comment]
Could you clarify why you think the code in the package isn't working, or suggest where the error in the code might be?

[Here's where we new up the Pushok client in the service provider](https://github.com/laravel-notification-channels/apn/blob/master/src/ApnServiceProvider.php#L25-L27) - it literally passes `$app['config']['broadcasting.connections.apn.production']` as the second argument to determine if it should be the production environment.

Can you confirm `config('broadcasting.connections.apn.production')` returns the expected value? Is it possible you have the app config cached with an old value?

**Comment by beyondthepale** [comment]
So when I printed out the message being sent to APN the relevant part showed this

Pushok\ClientisProductionEnv";b:0

It is sending a 0 for the boolean 'isProductionEnv'

And the response is Pushok\ResponsestatusCode";i:400  Pushok\ResponseerrorReason"; 'badDeviceToken'

The only way I could get the message sent to change to 

Pushok\ClientisProductionEnv";b:1

was to change the code to 

$customClient = new \Pushok\Client($authProvider, $production = true);

And the response is

Pushok\ResponsestatusCode";i:200

**Comment by beyondthepale** [comment]
I tested this over a 2 week period and always got the same result.

**Comment by beyondthepale** [comment]
So I just did another test after clearing the cache and configuration cache and got the same response.
when I used

'connections' => [
 'apn' => [
      'production' => env('APN_PRODUCTION', true),
    ],
],

The response was 

Pushok\Response�statusCode";i:400 Pushok\Response�errorReason"; 'badDeviceToken'

I noticed that the message sent did not appear to include any variable for the environment.

The message sent 

Pushok\Client�isProductionEnv";b:0

was when I attempted to use 

$options = [
'production' => true,
];
$customClient = new \Pushok\Client(\Pushok\AuthProvider\Token::create($options));

**Comment by dwightwatson** [comment]
In your last example you appear to be providing the `['production' => true]` option to the `Token` when it needs to be the second parameter to the `Client`.

Worth noting also that the [client is cached for 20 minutes](https://github.com/laravel-notification-channels/apn/blob/master/src/ClientFactory.php#L51-L56). See #103 for context around that. But if you have caching enabled in development it may also explain why you're seeing things that you don't expect.

---

I've just logged in to a production app and tested the following. I confirmed that the config is returning true as expected, then I created a new `Pushok\Client` out of the app container and dumped it to confirm that `isProductionEnv` is `true`.

```
>>> config('broadcasting.connections.apn.production')
=> true

>>> $client = app(Pushok\Client::class)
=> Pushok\Client {#5416}

>>> dump($client)
^ Pushok\Client^ {#5416
  ...
  -isProductionEnv: true
}
```

So - there is something going wrong on your end. 

---

If you could provide a sample repo that demonstrates the error I'll be happy to look into it further, but I am using this in production without issue and can't replicate it myself.

**Comment by beyondthepale** [comment]
"_In your last example you appear to be providing the ['production' => true] option to the Token when it needs to be the second parameter to the Client._"

Yes. I agree with this but this code came from your ReadMe file.

Per-message configuration
If you need to provide a custom configuration for a message you can provide an instance of a [Pushok](https://github.com/edamov/pushok) client and it will be used instead of the default one.

$customClient = new Pushok\Client(Pushok\AuthProvider\Token::create($options));

return ApnMessage::create()
    ->title('Account approved')
    ->body("Your {$notifiable->service} account was approved!")
    ->via($customClient)

Instead I used this which worked.

namespace App\Notifications;

public function toApn($notifiable)
    {
        $options = [
        'key_id' => env('APN_KEY_ID'), // The Key ID obtained from Apple developer account
        'team_id' => env('APN_TEAM_ID'), // The Team ID obtained from Apple developer account
        'app_bundle_id' => env('APN_BUNDLE_ID'), // The bundle ID for app obtained from Apple developer account
        'private_key_path' => env('APN_PRIVATE_KEY'), // Path to private key
        'private_key_secret' => null,// Private key secret
        ];

        $authProvider = AuthProvider\Token::create($options);

        $customClient = new \Pushok\Client($authProvider, $production = true);

        $request = ApnMessage::create()
            
            ->badge(1)
            ->title($this->title)
            ->sound('default')
            ->body($this->text)
            ->via($customClient);

            $stringRequest = serialize($request);
            log::info("Driver Message APNS is " . $stringRequest);
            return $request;
    }

And the message sent to APN was this (i have removed some senstitve token info)

Driver Message APNS is O:35:"NotificationChannels\Apn\ApnMessage":21:{s:5:"title";s:45:"Hi Peter, From:   Rosehill To: Castle Hill  a";s:8:"subtitle";N;s:4:"body";s:116:"Hi Peter, From:   Rosehill To: Castle Hill  at: 7:33am on Saturday 20th August.
 Please check My Bookings to accept.";s:5:"badge";i:1;s:5:"sound";s:7:"default";s:8:"category";N;s:8:"threadId";N;s:16:"contentAvailable";N;s:11:"titleLocKey";N;s:12:"titleLocArgs";N;s:12:"actionLocKey";N;s:6:"locKey";N;s:7:"locArgs";N;s:6:"custom";a:0:{}s:7:"urlArgs";a:0:{}s:8:"pushType";N;s:9:"expiresAt";N;s:10:"collapseId";N;s:6:"client";O:13:"Pushok\Client":8:{s:28:"^@Pushok\Client^@notifications";a:0:{}s:27:"^@Pushok\Client^@authProvider";O:25:"Pushok\AuthProvider\Token":7:{s:32:"^@Pushok\AuthProvider\Token^@token";s:274:"XXXXXXXXX";s:41:"^@Pushok\AuthProvider\Token^@privateKeyPath";s:70:"/home/mycabdrivercomau/mycabdriver.com.au/iOSKey/AuthKey_XXXXXXXXX.p8";s:44:"^@Pushok\AuthProvider\Token^@privateKeyContent";N;s:43:"^@Pushok\AuthProvider\Token^@privateKeySecret";N;s:32:"^@Pushok\AuthProvider\Token^@keyId";s:10:"XXXXXXXXXXX";s:33:"^@Pushok\AuthProvider\Token^@teamId";s:10:"6WNXXXXXX";s:38:"^@Pushok\AuthProvider\Token^@appBundleId";s:31:"com.driver.XXXXXX.XXXXX";}s:30:"^@Pushok\Client^@isProductionEnv";b:1;s:35:"^@Pushok\Client^@nbConcurrentRequests";i:20;s:39:"^@Pushok\Client^@maxConcurrentConnections";i:1;s:35:"^@Pushok\Client^@autoCloseConnections";b:1;s:30:"^@Pushok\Client^@curlMultiHandle";N;s:26:"^@Pushok\Client^@curlOptions";a:0:{}}s:14:"mutableContent";N;s:11:"customAlert";N;}


But I still maintain that 

broadcasting.php

'connections' => [

    'apn' => [

        'production' => env('APN_PRODUCTION', true),
    ],
],

resulted in a message being sent to APN that includes many variables which I printed out but did not include any environment variable. 

Driver Message APNS is O:35:"NotificationChannels\Apn\ApnMessage":21:{s:5:"title";s:45:"Sorry but your booking from:   Parramatta To:";s:8:"subtitle";N;s:4:"body";s:121:"Sorry but your booking from:   Parramatta To: Glebe at: 7:30pm on Friday 19th August has been cancelled by the Customer.
";s:5:"badge";i:1;s:5:"sound";s:7:"default";s:8:"category";N;s:8:"threadId";N;s:16:"contentAvailable";N;s:11:"titleLocKey";N;s:12:"titleLocArgs";N;s:12:"actionLocKey";N;s:6:"locKey";N;s:7:"locArgs";N;s:6:"custom";a:0:{}s:7:"urlArgs";a:0:{}s:8:"pushType";N;s:9:"expiresAt";N;s:10:"collapseId";N;s:6:"client";N;s:14:"mutableContent";N;s:11:"customAlert";N;}

i have another app on the app store in where this approach did work but I have now realised that this is because this app was created with a development provisioning profile.

The current app that I am testing from the app store was created correctly with a "production" or distribution provisioning profile and therefore required the message sent to apn to include 

Pushok\ClientisProductionEnv";b:1

which the broadcasting.php approach above did not.

The important thing here is what message is being sent to APN and what response is being received from APN. I do note however that there is no Token, AuthProviderToken or TeamId being sent in the message either.

**Comment by dwightwatson** [comment]
The README shows how to use a custom client if you want to:

```php
$customClient = new Pushok\Client(Pushok\AuthProvider\Token::create($options));
```

It doesn't give any indication of what the `$options` are, nor does it set the second parameter for the production environment - that's left to the developer. If you need a custom `Pushok\Client` then it's on you to configure it properly before passing it to the `ApnMessage`.

I'm not sure why you are using a custom client - is it only because you think the standard client isn't working of the box, or because you actually have a setup that requires a custom client for each notification?

---

Unfortunately there simply isn't enough information here to work out what is going on. You should verify that the [sample code in this comment](https://github.com/laravel-notification-channels/apn/issues/133#issuecomment-1221251470) is returning the same results that I am getting. 

If you can put together a sample repo that demonstrates this issue I'll explore further. But I am using this package in production and it works without problems (and I've tested it manually as a sanity check while working through this issue).

**Comment by beyondthepale** [comment]
So can I ask was the app that you are testing the package on created with a distribution provisional profile or a development provisional profile? This is important. 

In the aps environment string did you put "development" or "production"?

If you created the app store app with a development provisional profile the push notifications will work but the app is not actually a production app.

I have demonstrated that the standard client app is not sending any environment variable to APN in the message. In your understanding how does the standard client app advise APN that this is a push notification for a production app? If its not in the message sent to APN then where is it?

As I explained previously I am using the custom client because this is the only way that i could advise APN that this is a production push notification. Its not because I think the standard client doesn't work its because I have proven that it works in a development environment but not in a production environment. Its possible that this is because there is something wrong on my side but I cannot see any issue.

In my view your ReadMe file should explain to the developers (when using a custom client) how to advise APN that this is a production push notification. By adding a second variable. In my case I had to go through the Pushok documentation and figure this out for myself.

**Comment by dwightwatson** [comment]
I don't have access to the Apple Developer portal right now, but I have no reason to believe I'd be using development provisional profile. As I showed above my Laravel app is producing a `Pushok\Client` set to use production.

You're also the first person to suggest this is an issue - I would have expected others to run into the same issue you have had if it was a problem with the package out of the box.

You have demonstrated **there are issues in your app** but unless you can provide a repo for me to reliably replicate these issues then I can't do much more to help you. If you can narrow down the problem then feel free to PR it.

---

In my view when you use the exit hatch to pass a custom `Pushok\Client` in then the onus is on you to read the relevant documentation and configure it appropriately. I'll happily accept a PR that makes this clearer/includes `$production = true` as a second argument to the client. But the entire point of this package is abstract `Pushok` away from you so you shouldn't need to interact with it directly.

**Comment by beyondthepale** [comment]
I note that you haven't answered any of the questions I asked you.

"So can I ask was the app that you are testing the package on created with a distribution provisional profile or a development provisional profile? This is important.

In the aps environment string did you put "development" or "production"?

I have demonstrated that the standard client app is not sending any environment variable to APN in the message. In your understanding how does the standard client app advise APN that this is a push notification for a production app? If its not in the message sent to APN then where is it?

I am still waiting for an answer.
