### ISSUE TITLE
Handling 410 responses?

### ISSUE THREAD

**Issue by jonnott** [laravel-notification-channels/apn#134]
Before I used Laravel and this package, I used Pushok directly (in a non-Laravel codebase), and was able to handle 410 responses from the APN server (meaning the token used has expired / is invalid, i.e. the user's device no longer accepts push notifications for the app) .. something like:

```
$client = new Pushok\Client($authProvider);

$notifications = [];

// (build notifications)

$client->addNotifications($notifications);

$responses = $client->push();

foreach ($responses as $response) {
	if ($response->getStatusCode() == '410') {
		// remove this device token from local database, so we don't use it again
	}
}
```

Is it possible to achieve this with this package? What are other users of this package doing about 410 responses and/or expired tokens?

**Comment by dwightwatson** [comment]
If the response isn't an APNS_SUCCESS response then the package will dispatch the `Illuminate\Notifications\Events\NotificationEvent` event. You should be able to listen to that in your Laravel app and use that to handle tokens appropriately. [See `dispatchEvents` in the channel code to see when the event is fired and what additional data is passed into it](https://github.com/laravel-notification-channels/apn/blob/master/src/ApnChannel.php#L97-L104).

Hope this answers your question properly!
