### ISSUE TITLE
1. Push notification not working 2. Category feature not included

### ISSUE THREAD

**Issue by ReactiveXYZ-Dev** [laravel-notification-channels/apn#20]
1. Push notification are not delivered through localhost or https unless route to CA entrust file is added to Zend APN's AbstractBaseClient.php.
2. The package does not include action to add notification category which is crucial to enable actionable buttons on iOS.

**Comment by barryvdh** [comment]
1. Doesn't it use the systems certs? 
2. Can you submit a pr?

**Comment by ReactiveXYZ-Dev** [comment]
1. No apparently it does not since it didn't work both locally and remotely.
