### ISSUE TITLE
Feedback service is not connected

### ISSUE THREAD

**Issue by itsnotvalid** [laravel-notification-channels/apn#22]
APNS requires implementation of receiving feedback. Upstream `ZendService` has the classes `Client\Feedback` and `Response\Feedback` for this purpose. If this is not implemented, Apple can by their means to invalidate the certificates used.

**Comment by barryvdh** [comment]
Probably good to make a note of this in the readme with example. Care to pr.

**Comment by barryvdh** [comment]
#23 good for you?

**Comment by itsnotvalid** [comment]
Looks good, let me try it later, thanks.

**Comment by barryvdh** [comment]
Okay merged it for now, you can use it with `0.2.x@dev`
