### ISSUE TITLE
Auth Key

### ISSUE THREAD

**Issue by sicaboy** [laravel-notification-channels/apn#29]
Since Apple has simplified the way developers send notifications with a .p8 auth key. Any plan if this will be brought into this repository?

**Comment by dwightwatson** [comment]
If this is a new standard for how Apple wants push notifications to be sent then it's definitely something we should look into. The current dependency we use to send push notifications (Zend) looks unlikely to be updated to support such a change it would be a pretty substantial to swap it out for something else to support `.p8` keys. A good opportunity for a future release.

**Comment by antonioreyna** [comment]
@dwightwatson you could chck pushok looks like they can use auth key maybe is a good swap for zend

**Comment by dwightwatson** [comment]
Still open to this change - though I would like to see more about this change on Apple's end, and if they intend on phasing out the certificate-based approach (i.e. do we need to support both authentication methods, or is the auth key fine by itself?).

The [pushok](https://github.com/edamov/pushok) library (just linked to it for anyone else joining the discussion) is still under development and so might not be good to depend on it just yet - but definitely something to keep an eye on.

**Comment by zek** [comment]
I believe we should allow p8 keys

**Comment by dwightwatson** [comment]
I have pushed a *really early* first pass at replacing Zend with Pushok. 

Would love it if anyone who can has a go with the `develop` branch, and any other feedback on the PR would be greatly appreciated.

**Comment by dwightwatson** [comment]
About to tag version 1.0.0 which includes our new .p8 certificate support.
