### ISSUE TITLE
Problem while loading configuration

### ISSUE THREAD

**Issue by dazzcreations** [laravel-notification-channels/apn#30]
Hello,
I have used this package in my project, i have followed the installation guide properly but i am getting an error

Unresolvable dependency resolving [Parameter #2 [ <required> $environment ]] in class NotificationChannels\Apn\ApnChannel

and i am not able to solve it. 

If anyone can guide me it will be a great help.

**Comment by BadChoice** [comment]
Same here, could you solve it?

**Comment by BadChoice** [comment]
Ok, it was the service provider that was not being setup

**Comment by dwightwatson** [comment]
Yeah - sounds like you aren't registering the service provider.

We've added autodiscovery so this shouldn't be an issue in the next tagged release.
