### ISSUE TITLE
Connection ignores subsequent notifications if a single notification fails

### ISSUE THREAD

**Issue by mhsenpc** [laravel-notification-channels/apn#31]
Problem is when I am trying to send message to an array of tokens.if there is any problem in sending message to a device token,whole process would fail and next tokens wouldn't even proceeded.

**Comment by mhsenpc** [comment]
i fixed it

**Comment by dwightwatson** [comment]
You mention in the PR that Apple ignores any future requests on a given connection if a single push notification fails. Is there any documentation that indicates that this is how Apple treats connections after a failure, it seems like a bit of an oddity.

**Comment by dwightwatson** [comment]
Just merged #39 which now opens and closes connections for each token. Fixes an issue that sounds mightily similar to this one so this should be resolved now.
