### ISSUE TITLE
Update the version so we can use the getFeedback

### ISSUE THREAD

**Issue by BadChoice** [laravel-notification-channels/apn#33]
Just installed the package, and I notices that there isn't the `getFeedback` method,
I found that it is because in 0.1.0 wasn't there, but it is on the master now,

can you update the tag so we can get the feedback and remove the apropiate tokens?

Thanks!

**Comment by dwightwatson** [comment]
Just shipped v0.1.1 so you can start using the feedback feature in a tagged release.

**Comment by BadChoice** [comment]
Great! thank you,
If I'm correct, I should use the Feedback feature just after sending a push notification right?

**Comment by dwightwatson** [comment]
From my understanding it's not something you have to run directly after sending a notification, but rather something you should do regularly to ensure you're only pushing to valid tokens. I would think that a scheduled job would handle it just fine.
