### ISSUE TITLE
Push Notification + Laravel Task Scheduling + Cron Job

### ISSUE THREAD

**Issue by prafful-panwar** [laravel-notification-channels/apn#38]
I am writing a cron job that will run on a specific time every day and send all user to push notification but i am not receiving a push notification on an iOS device.

**This is my kernel.php file code**

`protected function schedule(Schedule $schedule)
    {
        $schedule->command('er:send-push-notification')
            ->dailyAt('13:00');
    }`

**this is my code in my ErCronJob.php**

`public function handle()
    {
        $users = User::whereIn('role_id', [2, 3, 4])->where('mobile_number', '9985353442')->get();
        foreach ($users as $user) {
            $message = $this->info('Hello user you got a new notification');
            $user->notify(new SendDailyComplaintStatisticsToErs($message));           
        }
    }`

**This is my code in SendDailyComplaintStatisticsToErs.php**
`public function toApn($notifiable)
    {
        return ApnMessage::create()
            ->badge(1)
            ->title('Account approved')
            ->body("Your account is approved!");
    }`

When i dump my last code i am getting below mention message.

![image](https://user-images.githubusercontent.com/4869823/36096553-e2b81eee-101c-11e8-9644-8c70216caf32.png)

**Can anyhelp me with this**. Thanks**

**Comment by dwightwatson** [comment]
Does the push notification work outside of the scheduled job? 

Also check that your notification isn't getting queued on your queue driver (and if it is, ensure that you've got a worker running locally).

**Comment by prafful-panwar** [comment]
@dwightwatson Thanks. It was a configuration issue for new APN channel.

**Comment by dwightwatson** [comment]
No worries. If you have a minute would you mind explaining the configuration issue you ran into a little more? We might be able to update the docs and prevent others from running into the same issue.
