### ISSUE TITLE
Service Provider?

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel-notification-channels/apn#41]
In the docs, it still states that "NotificationChannels\Apn\ApnServiceProvider::class" needs to be registered in app.php, but it appears this file was removed for the 0.2.0 release.

Is it still needed, or does this just need to be removed from the docs?

**Comment by dwightwatson** [comment]
Yeah, sorry - that needs to be removed. If we ever decide to re-introduce a service provider we can just autoload it instead. I'll fix this up.
