### ISSUE TITLE
No one notifications are not sent if one of push_token is wrong

### ISSUE THREAD

**Issue by dev31** [laravel-notification-channels/apn#44]
function routeNotificationForApn() in the User model returns array of push_tokens.
If the user has array of tokens (several devices), and one of them is wrong - no one devices will be notified.

**Comment by dev31** [comment]
I found that composer see only v0.1.1, but this issue was closed in v0.2.0
Please, update dependencies to the composer

**Comment by dev31** [comment]
Issue was fixed in v.0.2.0

**Comment by ash-allen** [comment]
Is it confirmed that this was fixed? I'm using v.0.4.0 and I have 5 tokens. My second token is invalid and so the 3rd, 4th and 5th push notifications never get sent.

I've logged the ``` foreach($tokens as $token) ``` loop in ApnChannel.php line 89. And it will only log the first 2 tokens. So it seems like the loop isn't continuing after the failure.

Any ideas? :)

**Comment by dwightwatson** [comment]
It may have been broken again - could you test on the latest version? Looks like part of the loop could be throwing an exception on a connection failure that might be the culprit. See if you can work out what's going on from your end and open a new issue with more info so we can sort it out.
