### ISSUE TITLE
Should sending to multiple tokens open a new connection each time?

### ISSUE THREAD

**Issue by wammy21** [laravel-notification-channels/apn#45]
I'm referencing to this part:

https://github.com/laravel-notification-channels/apn/blob/b8f45100dd1aee7727196fe519c0c5da3f0b011c/src/ApnChannel.php#L89

Should this not OpenConnection/CloseConnection outside of the foreach loop?

**Comment by wammy21** [comment]
I did see pr #39 however, according to the APNs development docs you should keep the connection open...

From: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1

> Best Practices for Managing Connections
> 
> Keep your connections with APNs open across multiple notifications; do not repeatedly open and close connections. APNs treats rapid connection and disconnection as a denial-of-service attack. You should leave a connection open unless you know it will be idle for an extended period of time—for example, if you only send notifications to your users once a day, it is acceptable practice to use a new connection each day.

The reason the user that provided the PR request was having issues with the connection dying when sending to multiple tokens is because one of the tokens was invalid (or was dev vs prod) in the group.

See this discussion here: https://stackoverflow.com/questions/2583957/apple-push-notification-sending-high-volumes-of-messages

While I understand for single user -> single device notifications this would be useless, say for example instead of the User model being the notifiable, it could be a Group model (which aggregates various User model's tokens, and sends out a single notification), this would create 1 new connection for each individual token and possibly get your app banned/throttled from APN per their guidelines above.

**Comment by dwightwatson** [comment]
I agree that the implementation at the moment isn't perfect and that we can probably do a better job here, but it exists as-is now to allow for using multiple tokens.

It would make sense to organise tokens into groups by connection and then only open each of those connections a single time. Whatever approach we end up using here we can probably roll out to the GCM channel too because there's a similar feature request there.

**Comment by wammy21** [comment]
I looked throught the old issues regarding this but I wasn't able to fully grasp what exactly was the issue before. 

Per what I've read we should be able to send the notification, check the connection and re-open if necesary? I'd love to work on a PR but I want to get more details on what you think could be done to accomplish this and make everyone happy :)

**Comment by dwightwatson** [comment]
Yeah I don't think that would be too hard. If you could sort the message objects by their connection then each time you loop to a new message you can check if it's got a different set of credentials and then close/open a new connection.

Your work in the other PR is the important first step in getting there so I'm excited to get that in.

**Comment by wammy21** [comment]
Let me get the other PR in and see if I can start working this out.

**Comment by wammy21** [comment]
Hey just checking into this issue. I've been trying to toy around with ways to work this out, I have a few questions:

Do we really need to go through the trouble of checking the message connections on each loop? I don't believe we are receiving multiple message instances, just a single message instance with multiple tokens:

in ApnChannel->send: 
```php
$tokens = (array) $notifiable->routeNotificationFor('apn', $notification); //array of tokens
 //...

$message = $notification->toApn($notifiable); //single message instance.
//...

$this->sendNotifications($notifiable, $notification, $tokens, $message);
```
So I feel we should be able to just loop through each token in `sendNotifications` method. The only issue I find is that we need to check if the message was in fact sent, and re open the connection if it failed?

Perhaps just implement a method in `InteractsWithConnection` called `isConnected` that just returns the value of $this->client->isConnected() and re-open the connection if it is false?

```php
$this->openConnection($message->credentials);

foreach ($tokens as $token) {

    if(!$this->isConnected()) {
        $this->openConnection($message->credentials);
    }

    $this->sendNotification(
        $notifiable,
        $notification,
        $this->adapter->adapt($message, $token),
         $token
    );

}

$this->closeConnection();
```


Althought, looking at Zend `AbstractClient` it does not seem that it is handling if a write fails (setting isConnected=false), although in `Message->send()` there is a catch for if `write` returns false, but that just throws an exception. Am I missing something? or does this make sense? seems there is no easy way to check if the connection was killed halfway through.

**Comment by dwightwatson** [comment]
We now use a new library under the hood for 1.0.0, so this is no longer an issue.
