### ISSUE TITLE
Notification::fake but something is done

### ISSUE THREAD

**Issue by BadChoice** [laravel-notification-channels/apn#48]
I'm using Notification::fake() to test the notifications but it looks like it does something since the test takes about 800ms to complete, when the other tests that are not using notifications just take 200ms

Let me know if there is anything I can to to verify that is doing something with the network

Thanks!

**Comment by dwightwatson** [comment]
Pull out your ethernet cable or turn off your WiFi and run the suite again. 😆

**Comment by BadChoice** [comment]
Hahaha, your are right

Yes, disconeciting from internet, I got the followin error::

```
"{"code":0,"error":"Unknown error: NotificationChannels\\Apn\\Exceptions\\ConnectionFailed, Cannot connect to APNs: Unable to connect: tls:\/\/feedback.sandbox.push.apple.com:2196: 2 (stream_socket_client(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known) at \/Users\/badchoice\/git\/web\/revo-loyalty\/vendor\/laravel-notification-channels\/apn\/src\/Exceptions\/ConnectionFailed.php : 16","data":[]}"
```

so it looks like it tryies to connect even when using the `Notification::fake()`

**Comment by dwightwatson** [comment]
That's interesting. Are you definitely calling `Notification::fake()` before any calls to the app?

I can't think of a reason this library would be treated differently to other channels under the hood.

**Comment by dwightwatson** [comment]
Cool, thanks for sharing the test code.

I've just tested very simply locally that when I call `Notification::fake()` before attempting to fire off a notification over the `ApnChannel` that it doesn't get fired.

```php
Route::get('/test', function () {
    Notification::fake();

    $user = App\User::first();
    $comment = App\Comment::first();

    $user->notify(new App\Notifications\Comments\NewComment($comment));
});
```

I'm really not sure what to suggest next as it's not easily reproducible. I would've suggested that it was something with your app, but that doesn't make sense as you indicated that `Notification::fake()` works in other tests/for other drivers.

**Comment by BadChoice** [comment]
There something uncommon in my app and is that I have an aplication for each user, so each user has their own certificate

I use a function to update the it with:

```
    public static function setup()
    {
        $useSandbox = false;
        Config::set('broadcasting.connections.apn', [
            'environment' => $useSandbox ? ApnChannel::SANDBOX : ApnChannel::PRODUCTION,
            'certificate' => self::getApnCertificatePath($useSandbox),
            'pass_phrase' => null, // Optional passPhrase
        ]);
```

Which I use in the controller before sending the push, but this shouldn't do anything right?

**Comment by BadChoice** [comment]
Ok.. found it...
I was calling the feedback to cleanup old tokens after sending the notification

Sorry for the confusion and thank you so much for your help and awesome package!
