### ISSUE TITLE
Use multiple certificates

### ISSUE THREAD

**Issue by PauBenetPrat** [laravel-notification-channels/apn#52]
Hi, 
I'd like to use diferent certificates with your package. Is there any way to achieve this?

I'm using one normal notification certificate and I want to add a passKit certificate to notify iOS wallet for updates. It can not be the same...

**Comment by dwightwatson** [comment]
No, we don't support that functionality currently. Open to PRs that would want to implement it however.

**Comment by PauBenetPrat** [comment]
At the end, I temporary setup an specific certificate before sending my custom notification. 
The is no need for PR. Thanks!
```
        Config::set('broadcasting.connections.apn', [
            'environment' => 1,
            'certificate' => self::getApnCertificatePath($passType),
            'pass_phrase' => null, // Optional passPhrase
        ]);
        (new ApnServiceProvider(app()))->boot();
```

**Comment by dwightwatson** [comment]
Following in the footsteps of [Laravel's Nexmo channel's approach to this problem](https://github.com/laravel/nexmo-notification-channel/pull/30) I've added a `via` method on the message that allows you to pass in a custom `Pushok\Client` configured to your needs.

**Comment by BadChoice** [comment]
👏 👏 
Thank you!

**Comment by RoduanKareemAldeen** [comment]
Hello @PauBenetPrat ,
I'm implementing this channel to send updates to apple wallet also. can you show me exactly how did you do it yourself.
