### ISSUE TITLE
0.4.0 not showing in Packagist

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel-notification-channels/apn#54]
It appears that the latest version, v0.4.0 (https://github.com/laravel-notification-channels/apn/releases/tag/v0.4.0) isn't showing in Packagist. Is there something that needs to be done in order to get that to show as available?

**Comment by aaronhuisinga** [comment]
@dwightwatson it looks like you tagged the release, but it still isn't showing as available.

**Comment by dwightwatson** [comment]
Hm - I suspect the Packagist webhook may be out of date and that's why the tag hasn't synced through. 

@barryvdh I don't suppose you have access on Packagist to check this, or would Mohamed have that?

**Comment by barryvdh** [comment]
I think only @themsaid

**Comment by aaronhuisinga** [comment]
@themsaid have you had a chance to look into this? We're still forced to pull from dev-master on 5.8

**Comment by cmorbitzer** [comment]
@themsaid Bumping this to see if there's an update

**Comment by aaronhuisinga** [comment]
The release is now showing in Packagist. Closing this.
