### ISSUE TITLE
How/Where does the feeback server get used?

### ISSUE THREAD

**Issue by tobz-nz** [laravel-notification-channels/apn#55]
I don't understand where to use the feedback service. Is it in a controller? 
how is that url registered?

Is it in a service provider? Expanding the docs on this would be veru useful and appreciated.

**Comment by DaanGeurts** [comment]
From what I understand from the APNS documentation is that you should check the APNS service regularly to fetch a list with device tokens that are not valid anymore and should be updated or removed from your service. I guess you should use the FeedBackService in a scheduled queued job. Am I right @barryvdh @dwightwatson ?

**Comment by dwightwatson** [comment]
Yeah, we could probably do with a better job explaining what you're meant to do with that. I'm not totally familiar with how it works with respect to pagination and so on, but a scheduled job that runs at a reasonable frequency for the sort of volume you're sending should do the trick.

**Comment by tobz-nz** [comment]
Right. Do you have a job you could easiiy chuck in here, or would it be useful for me to PR one?
I don't have a huge amount of time at the moment, but will get it done at some point anyway - if someone else doesn't.

**Comment by dwightwatson** [comment]
I don’t think we can supply a job because everyone’s token removal will be different. Unless we provided a stub to get people started? Open to ideas.

**Comment by tobz-nz** [comment]
True.. yes a stub should work. Sort out everything that can be done and leave final removal implementation to the user. 👍
