### ISSUE TITLE
Update version so we can use expire on Message

### ISSUE THREAD

**Issue by rwblue** [laravel-notification-channels/apn#58]
Using the package for the while, and i found that we cannot set the expire for the Message 

can you update, so we can set the expire value

thank you and cheers ^^

**Comment by dwightwatson** [comment]
Happy to look at any PR that introduces the functionality.

**Comment by dwightwatson** [comment]
This required some work cleaning up the abstractions under the hood, but got a PR ready to go. If you've got any feedback on that please let me know.
