### ISSUE TITLE
Update Packagist webhooks so updates are automatic

### ISSUE THREAD

**Issue by dwightwatson** [laravel-notification-channels/apn#62]
Looks like the sync between GitHub releases and Packagist isn't working anymore and needs to be updated to use the newer webhooks method. This will allow us to keep publishing new versions.

@themsaid I believe you're the admin of the package on Packagist - would you be able to update the webhook, or add me as a maintainer on Packagist (dwightwatson) so that I can sort it out going forward?

Relevant: #60

**Comment by atymic** [comment]
Github hooks should be syncing with packagist properly now. If there are any issues in the future ping me 😄

**Comment by atymic** [comment]
I've also added you as a maintainer @dwightwatson in case there are any future issues.

**Comment by dwightwatson** [comment]
Awesome, thanks for that @atymic
