### ISSUE TITLE
Can't find the class ApnChannel

### ISSUE THREAD

**Issue by yuriypasternak** [laravel-notification-channels/apn#68]
Hi there,

After I add Apn record into config/broadcasting.php
I got an exception "Class 'ApnChannel' not found" 

I have tried adding the path "vendor/laravel-notification-channels/apn/src" to composer.json 
`"autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories",
            "vendor/laravel-notification-channels/apn/src"
        ]
    },`

and running **artisan package:discover**, it does show 
**Discovered Package: laravel-notification-channels/apn**

However, still gives 'Class not found' issue. Any help much appreciated!

Laravel 5.8

**Comment by dwightwatson** [comment]
Did you actually import the proper class? Looks like your app is looking for ApnChannel in the root namespace.

```
use NotificationChannels\Apn\ApnChannel;
```

**Comment by dwightwatson** [comment]
Also, what are you putting in broadcasting.php? There’s no reference to the channel class in there.

**Comment by yuriypasternak** [comment]
Thank you for your prompt reply. It works fine now, 
as per instructions, the following record must be added to broadcasting.php: 

```
`'apn' => [
            'environment' => ApnChannel::PRODUCTION, // Or ApnChannel::SANDBOX
            'certificate' => '/certs/dev.pem', 
            'pass_phrase' => 'pass123', 
],`
```
which does reference **ApnChannel** and at this point ApnChannel was not visible

**Comment by dwightwatson** [comment]
Gotcha. Happy to accept a PR to the docs if you think it’s an improvement 🙂
