### ISSUE TITLE
Question: is this using the legacy api?

### ISSUE THREAD

**Issue by jstolp** [laravel-notification-channels/apn#70]
I read on Apple developer that the legacy (binary/http1.1) api would [be deprecated in November 2020](https://developer.apple.com/news/?id=11042019a). 

Is this plugin using the new HTTP/2 API?

**Comment by dwightwatson** [comment]
No - please see #67 for a new branch that supports the newer API. Unfortunately I don't currently have access to .p8 keys so I can't test it, but am hoping eventually will be able to and report back if it works - and if it does I can merge it in.

**Comment by jstolp** [comment]
Thanks! I can help with testing, if you would like :)

**Comment by dwightwatson** [comment]
Please - give the branch a go and let me know of any issues you run into. I'm just reluctant to merge it into master as the new major version if it doesn't actually work.
