### ISSUE TITLE
need support ios 13 background pushes

### ISSUE THREAD

**Issue by hammamm** [laravel-notification-channels/apn#71]
the library does not support pushs in background in ios 13, it works fine when set content availble as 1 and send no title and body in olders system version of ios 12 or lower, but when using ios 13 it does not work fine

**Comment by dwightwatson** [comment]
Please see the open PR to introduce a new library under the hood with .p8 certificates. If you pull that code in does it resolve this problem?

**Comment by dwightwatson** [comment]
About to tag version 1.0.0 which includes our new .p8 certificate support. Please see if this new version resolves your issue and re-open if it does not.
