### ISSUE TITLE
Enable push notifications in laravel?

### ISSUE THREAD

**Issue by yacoanix** [laravel-notification-channels/apn#72]
Hello, I would like to know if it is necessary to enable push notifications in my app. I have never used Xcode and I don't know if I can activate this feature to my Laravel project.

**Comment by dwightwatson** [comment]
Yes, there’s quite a bit of setup required on the iOS side of things, including provisioning certificates through the developer portal and configuring them in Xcode. You’ll need to refer to Apple’s documentation on setting it up, and once you’re able to get your app’s push tokens to Laravel you can start using this package. Hope this helps.

**Comment by yacoanix** [comment]
Hello, I have tried to connect my Laravel project in Xcode to enable push notifications and it has been impossible because it is not an Xcode project, could you give me some guidelines to do this step?

**Comment by dwightwatson** [comment]
Your Laravel app doesn't go into Xcode - your iOS app goes into Xcode. I don't have the documentation to configure the iOS app for push notifications but the Apple documentation should cover everything you need. I'm only able to provide support specific to the usage of this package with Laravel.

Once you've done that you can install this package, and using the certificates you generated during the iOS setup you can then send start sending push notifications through the notification channels.
