### ISSUE TITLE
How to get the push tokens?

### ISSUE THREAD

**Issue by yacoanix** [laravel-notification-channels/apn#73]
Hi, I have a question about the library. I created the .pem certificate and when doing the command "openssl s_client -cert Push.pem -connect gateway.push.apple.com:2195" this has not occurred any error so I suppose it is ok. I have continued to configure broadcasting and created the notification but it has not worked.
In my broadcasting:

`'apn' => [
            'environment' => NotificationChannels\Apn\ApnChannel::PRODUCTION, // Or ApnChannel::SANDBOX
            'certificate' => base_path('Push.pem'),
            'pass_phrase' => null,
        ],`

In my notification:
`namespace App\Notifications;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Support\Facades\Log;
use NotificationChannels\Apn\ApnChannel;
use NotificationChannels\Apn\ApnMessage;

class ApnPushPruebaNotification extends Notification
{
    use Queueable;

    public function via($notifiable)
    {
        return [ApnChannel::class]; // Make sure you use 'ApnChannel::class', not just 'apn'
    }

    public function toApn($notifiable)
    {
        return ApnMessage::create()
            ->badge(1)
            ->title('Account approved')
            ->body("Your {$notifiable->service} account was approved!");
    }

}`

in my notifiable (User):
`
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
class User extends Authenticatable
{
    use Notifiable;

	protected $table = 'users';

    protected $fillable = [
	'name', 
	'email', 
        'phone',
        'photo',
	'password',
        'type',
        'apn_token'
    ];
public function routeNotificationForApn()
    {
        return $this->apn_token;
    }
}`

and the function in controller (with "use App\Notifications\ApnPushPruebaNotification") :
`
public function test()
    {
        $user = Auth::user();
        $user->notify(new ApnPushPruebaNotification());

    }
`
My question is where do I get the apn tokens? For knowing if that fails, or is something else, thanks for the help.

**Comment by dwightwatson** [comment]
When you request permission to send push notifications in your iOS app it will give you a push token to use. You should then send that push token to your server (provide an API endpoint or some other way to deliver it) and then save it however you want. You could have a `push_tokens` table if you wanted to have multiple tokens per user, or a `push_token` field on the users table if you only wanted one per user.

**Comment by yacoanix** [comment]
OK thank you very much, I already know my problem. My problem is that I didn't know that I necessarily need an IOS app. I thought it would be useful for a website. What I didn't know is that it is created for a Laravel API. Once again, thank you very much.
