### ISSUE TITLE
How to use multiple bundle ids?

### ISSUE THREAD

**Issue by dilipdk** [laravel-notification-channels/apn#83]
i have two applications with single back end. so i want to use multiple bundle ids to send push notifications to the ios devices. can you please help me to resolve this asap. thanks

**Comment by dwightwatson** [comment]
Please see the [`via` method](https://github.com/laravel-notification-channels/apn#per-message-configuration) on the message object. You can configure a custom Pushok client to use for a given message. Check out the `ApnServiceProvider` to see how we build a Pushok client, or check their docs to see how to configure it as you need.
