### ISSUE TITLE
1.0.0+ not working with Laravel Vapor

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel-notification-channels/apn#85]
This is more of a PSA than an actual issue, but I felt it make sense to open this. Since the switch to using Pushok for sending notifications, this package currently does not work with Laravel Vapor.

This is due to Pushok requiring curl being compiled with HTTP/2 enabled, and Vapor (currently) not meeting this requirement. I have submitted a ticket to the Vapor team (about a week ago) regarding this, but as of now have not received a response to it.

This is an issue, because in order to upgrade to Laravel 7, we're required to use >= v2.0.0 of this package, which is currently not possible due to the Pushok incompatibility.

It seems to me there are 3 possible solutions here:
1. Tagging an older version of this package with Laravel 7 support
2. Getting the Laravel team to update Vapor to support HTTP/2 with curl
3. Somehow overriding the Pushok code to not use HTTP/2

1 and 2 are certainly better solutions, but for the time being we're stuck on Laravel 6 since we're using Vapor for our environment.

**Comment by aaronhuisinga** [comment]
@themsaid I'm tagging you here to loop you in on this issue preventing anyone using this package (170k+ installs on Packagist) from updating to Laravel 7 while using Laravel Vapor for their infrastructure.

**Comment by dwightwatson** [comment]
Hey, thanks for bringing this to my attention.

The switch to Pushok was a major change under the hood for this package and seemed like a good opportunity to start fresh.

I've just tagged `v0.6.0` which is just an extended release from the older version that can be installed alongside Laravel 7.0. It's not as nice to use as the latest version but will get you by if necessary. 

Long term though it would be ideal to see the issue resolved on Vapor. It makes sense to me that curl should be compiled with `HTTP/2` support but I'm not sure how involved that becomes. Hopefully Mohamed can give us more insight there, and if there is any ETA on it.

**Comment by aaronhuisinga** [comment]
@dwightwatson I went through the process and figured out how to add HTTP/2 support to Vapor builds. PR is open at https://github.com/laravel/vapor-php-build/pull/31. We're using a custom Lambda layer built off of my PR and it's working as expected!

**Comment by dwightwatson** [comment]
Awesome, nice work putting that together. Hoping it will make it into the core 🤞

**Comment by aaronhuisinga** [comment]
My PR with HTTP/2 support was just merged into Vapor. Closing this issue as it's now resolved.
