### ISSUE TITLE
How to send push notifications to multiple users

### ISSUE THREAD

**Issue by dilipdk** [laravel-notification-channels/apn#86]
I need to send notifications to multiple users at same time. could you please help me to resolve this. if you have any example application it will be helpful for me. thanks

**Comment by dwightwatson** [comment]
Please read the Laravel docs on this. You can send a notification to multiple users using the facade.

```php
use Illuminate\Support\Facades\Notification;

Notification::send($users, new MyNotification);
```

**Comment by dilipdk** [comment]
Thank you
