### ISSUE TITLE
pushType doesn't work properly

### ISSUE THREAD

**Issue by chimit** [laravel-notification-channels/apn#88]
I'm using this package version v1.3.0 with Lumen 6 because Lumen 7 hasn't been released yet.

If I use a `pushType()` method to send `voip` notifications I get a `DeviceTokenNotForTopic` error. But if I change `APN_BUNDLE_ID` env var by adding a `.voip` suffix it starts working. Apparently, edamov/pushok [supports](https://github.com/edamov/pushok/issues/78) this case.

```php
ApnMessage::create()
    ->pushType('voip')
    ->badge(1)
    ->title('Incoming call')
    ->body('Something here!');
```

**Comment by dwightwatson** [comment]
I'm not sure what change needs to be made - is this an issue on our end or Pushok? 

If it's an issue on our end could you please make a PR that resolves it and I'll review.

**Comment by chimit** [comment]
I'm not sure, so I would like to ask somebody to bring some clarity here :)

**Comment by dwightwatson** [comment]
We map the call to `pushType` straight back in to Pushok... all that magic under the hood happens in their library. I haven't used that argument myself so I don't have any additional insight unfortunately.

**Comment by chimit** [comment]
This issue can be closed as long as the problem is fixed by https://github.com/laravel-notification-channels/apn/pull/92
