### ISSUE TITLE
Normal and voip push notifications should be sent to different tokens

### ISSUE THREAD

**Issue by chimit** [laravel-notification-channels/apn#89]
It's not enough just to specify a `voip` push type to turn a traditional push notification into a VoIP push notification. Every iOS device has two different device tokens: `alarm` (normal) and `voip`. So both should be stored in the DB and retrieved by the `routeNotificationFor...` method. Apparently, something like a new `routeNotificationForApnVoip` method is needed.

**Comment by dwightwatson** [comment]
Does it deserve to be a different channel? Does it require the message to be different to a standard push notification? I wonder if we could subclass the channel into a specific VOIP channel that calls a separate routing method.

**Comment by chimit** [comment]
Just for the full picture. Currently, Apple uses 2 frameworks for push notifications: [UserNotifications Framework](https://developer.apple.com/documentation/usernotifications) and [PushKit Framework](https://developer.apple.com/documentation/pushkit). They use different tokens.

There are 6 types of push notifications:

1. `alert` (UserNotifications)
2. `background` (UserNotifications)
3. `voip` (PushKit)
4. `complication` (PushKit)
5. `fileprovider` (PushKit)
6. `mdm` (?)

I guess if we want to keep one `routeNotificationForApn` method we need to change its result structure from a plain array of tokens to an associative array like this:

```php
[
    [
        'alarm' => 'token1',
        'voip' => 'token2',
    ],
    [
        'alarm' => 'token3',
        'voip' => 'token4',
    ],
]
```

The message structure for both UserNotifications tokens and PushKit tokens are very similar.

**Comment by dwightwatson** [comment]
So in effect there are two types of tokens that belong to different notification systems?

I don't think it's wise to muddy up a single `routeNotificationForApn` method to collect tokens for different systems.

I'd be inclined to leave the default as the UserNotifications channel, and continue to use `routeNotificationForApn`. And then introduce a `ApnVoipChannel` that calls `routeNotificationForApnVoip`. It might need it's own `toApnVoip` method as well in case you want to provide a different message for that channel.

Happy to put a PR together for this if you want to have a look. But at a high level I don't think we should try and force both frameworks through the one channel if they have enough differences.

**Comment by chimit** [comment]
> The PushKit framework supports specialized notifications for updating your watchOS complications, responding to file provider changes, and receiving incoming Voice-over-IP (VoIP) calls. PushKit notifications differ from the ones you handle with the UserNotifications framework. Instead of displaying an alert, badging your app’s icon, or playing a sound, PushKit notifications wake up or launch your app and give it time to respond. Both PushKit and UserNotifications use the Apple Push Notification service (APNs) to deliver push notifications to user devices.

So there is still only one notification system for both push types (frameworks) – APNS. Separation looks logical, but Apple doesn't separate [payload structure](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/) in their documents, so they still consider APNS messages as one entity.

In addition to my previous array example, maybe it's better to use framework names as keys:

```php
[
    [
        'un_token' => 'token1', // `un` for UserNotifications framework
        'pk_token' => 'token2', // `pk` for PushKit framework
    ],
    [
        'un_token' => 'token3',
        'pk_token' => 'token4',
    ],
]
```

**Comment by dwightwatson** [comment]
I'm still confused by your example - do you need a User Notification token AND a PushKit token in order to send a VOIP notification? Why are you putting `token1` and `token2` in one array and `token3` and `token4` in another?

**Comment by chimit** [comment]
Yes, you are right. We don't need both tokens to send one push notification.
