### ISSUE TITLE
critical alert support

### ISSUE THREAD

**Issue by ExeErik** [laravel-notification-channels/apn#94]
I would like to create critical alerts (see https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2990112).
I need to include the "critical" and "volume" flag in the sound dictionary. As I see it is only possible to set a sound name.

Is it possible to add this flag?

**Comment by dwightwatson** [comment]
If you can provide a PR or point me to how to do this with the Pushok library I’ll look to make the change.

**Comment by ExeErik** [comment]
closed, the pushok library doesn't support critical alerts right now

**Comment by dan-lee** [comment]
It looks like it does now: https://github.com/edamov/pushok/releases/tag/0.11.4

And we already got it working like this:

```php
use Pushok\Payload\Sound;

ApnMessage::create()
  ->sound(
    Sound::create()
      ->setCritical(1)
      ->setName('sound.mp3')
      ->setVolume(1.0)
  )
  ->title('Title')
  ->body('Body');
```
