### ISSUE TITLE
Certificate authentication disabled?

### ISSUE THREAD

**Issue by radu-mymed** [laravel-notification-channels/apn#99]
I'm upgrading a project to laravel-notification-channels/apn 1.3.0 (Laravel 6) and it appears that the service provider is hardcoded on `Token` with no way to use the `Certificate` class of edamov/pushok without writing an override service.

Is my understanding correct? And is that a bug, or is it a feature that is supposed to force me to get some new stuff from Apple?

**Comment by dwightwatson** [comment]
We switched the underlying library to pushok to support tokens as that seemed like the direction Apple was moving towards. 

Is there a reason for staying on certificates, or just haven’t had a need to change?

You can keep using the version of the package you’re on, or override the service provider.

**Comment by radu-mymed** [comment]
Oh... I didn't do my research correctly. I can use version 0.6.0 and keep at upgrading Laravel (5.5 -> 6) in my project, and worry about the Token authentication later. I had version 0.2.0 in there, and I was a bit too eager to upgrade to the latest version of the library.

I'd rather not override the service provider because that sort of stuff has a habit of coming back to bite me somewhere down the road.

**Comment by dwightwatson** [comment]
I understand where you're coming from. If there was a common reason for people to continue using certificates we could update the service provider to bind against the `AuthProviderInterface` instead of the `Token` directly - which would give people the flexibility to pass in their `Certificate` credentials instead.

I'll close this for now but happy to revisit if necessary.

**Comment by Artash123** [comment]
I have just such a problem right now, I have a .pem certificate, and to send a notification I need to change the service provider (create a Сertificate instead of a Token). It will be great if you update
